
#you must login on my.xver before use
import time
import pyautogui as pg
pg.hotkey('win','r')
pg.write('chrome')
pg.hotkey('enter')
time.sleep(1)
pg.write("https://my.xver.cloud")
pg.press('enter')
pg.press('f11') 


time.sleep(2)
pg.click(1250,110)  #click depoly server
time.sleep(1)
pg.click(625,315)  #select server linux
pg.hotkey('down')
pg.hotkey('enter')
time.sleep(1)
pg.click(638,450) #click plan server
pg.hotkey('tab')
pg.write('Muffyn29300.') #write password
pg.hotkey('tab')
pg.write('muffyn1')     #name server
pg.hotkey('enter')

time.sleep(2)
pg.click(100,564) #click ตรงขอบ Point(x=100, y=564)
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.press('enter')
time.sleep(2)
pg.click(625,315) #select server linux
pg.hotkey('down')
pg.hotkey('enter')
time.sleep(1)
pg.click(638,450) 
pg.hotkey('tab')                        
pg.write('Muffyn29300.')
pg.hotkey('tab')
pg.write('muffyn2')
pg.hotkey('enter') 

# loop 13 times
time.sleep(2)
pg.click(100,564) #click ตรงขอบ Point(x=100, y=564)
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.press('enter')
time.sleep(2)
pg.click(625,315) #select server linux
pg.hotkey('down')
pg.hotkey('enter')
time.sleep(1)
pg.click(638,450) 
pg.hotkey('tab')
pg.write('Muffyn29300.')
pg.hotkey('tab')
pg.write('muffyn3')
pg.hotkey('enter') 

time.sleep(2)
pg.click(100,564) #click ตรงขอบ Point(x=100, y=564)
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.press('enter')
time.sleep(2)
pg.click(625,315) #select server linux
pg.hotkey('down')
pg.hotkey('enter')
time.sleep(1)
pg.click(638,450) 
pg.hotkey('tab')
pg.write('Muffyn29300.')
pg.hotkey('tab')
pg.write('muffyn4')
pg.hotkey('enter') 

time.sleep(2)
pg.click(100,564) #click ตรงขอบ Point(x=100, y=564)
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.press('enter')
time.sleep(2)
pg.click(625,315) #select server linux
pg.hotkey('down')
pg.hotkey('enter')
time.sleep(1)
pg.click(638,450) 
pg.hotkey('tab')
pg.write('Muffyn29300.')
pg.hotkey('tab')
pg.write('muffyn5')
pg.hotkey('enter') 

time.sleep(2)
pg.click(1079,346) #click ตรงขอบ Point(x=100, y=564) Point(x=1079, y=346)
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.press('enter')
time.sleep(2)
pg.click(625,315) #select server linux
pg.hotkey('down')
pg.hotkey('enter')
time.sleep(1)
pg.click(638,450) 
pg.hotkey('tab')
pg.write('Muffyn29300.')
pg.hotkey('tab')
pg.write('muffyn6')
pg.hotkey('enter') 

time.sleep(2)
pg.click(1079,346) #click ตรงขอบ Point(x=100, y=564) Point(x=1079, y=346)
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.press('enter')
time.sleep(2)
pg.click(625,315) #select server linux
pg.hotkey('down')
pg.hotkey('enter')
time.sleep(1)
pg.click(638,450) 
pg.hotkey('tab')
pg.write('Muffyn29300.')
pg.hotkey('tab')
pg.write('muffyn7')
pg.hotkey('enter') 

time.sleep(2)
pg.click(1079,346) #click ตรงขอบ Point(x=100, y=564) Point(x=1079, y=346)
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.press('enter')
time.sleep(2)
pg.click(625,315) #select server linux
pg.hotkey('down')
pg.hotkey('enter')
time.sleep(1)
pg.click(638,450) 
pg.hotkey('tab')
pg.write('Muffyn29300.')
pg.hotkey('tab')
pg.write('muffyn8')
pg.hotkey('enter') 

time.sleep(2)
pg.click(1079,346) #click ตรงขอบ Point(x=100, y=564) Point(x=1079, y=346)
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.press('enter')
time.sleep(2)
pg.click(625,315) #select server linux
pg.hotkey('down')
pg.hotkey('enter')
time.sleep(1)
pg.click(638,450) 
pg.hotkey('tab')
pg.write('Muffyn29300.')
pg.hotkey('tab')
pg.write('muffyn9')
pg.hotkey('enter') 

time.sleep(2)
pg.click(1079,346) #click ตรงขอบ Point(x=100, y=564) Point(x=1079, y=346)
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.press('enter')
time.sleep(2)
pg.click(625,315) #select server linux
pg.hotkey('down')
pg.hotkey('enter')
time.sleep(1)
pg.click(638,450) 
pg.hotkey('tab')
pg.write('Muffyn29300.')
pg.hotkey('tab')
pg.write('muffyn10')
pg.hotkey('enter') 

time.sleep(2)
pg.click(1079,346) #click ตรงขอบ Point(x=100, y=564) Point(x=1079, y=346)
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.press('enter')
time.sleep(2)
pg.click(625,315) #select server linux
pg.hotkey('down')
pg.hotkey('enter')
time.sleep(1)
pg.click(638,450) 
pg.hotkey('tab')
pg.write('Muffyn29300.')
pg.hotkey('tab')
pg.write('muffyn6=11')
pg.hotkey('enter') 
time.sleep(1)

time.sleep(1)
pg.hotkey('f11')
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.keyDown('tab')
pg.hotkey('tab')    
pg.keyDown('tab')
time.sleep(1)
pg.write('finished bro!') 


  
