import time

import pyautogui as pg #nickname bro!!
pg.write('sudo apt update && sudo apt upgrade -y')
pg.press('enter')
time.sleep(5)
pg.write('y')
pg.sleep(10)
pg.write('sudo apt install lightdm')
pg.sleep(10)
pg.write('y')
pg.press('enter')
pg.write('sudo apt install tasksel')
pg.sleep(10)
pg.write('y')
pg.press('enter')
pg.sleep(100)
pg.press('down')
pg.press('enter')
pg.sleep(1000)
pg.write('tasksel')
pg.press('enter')
pg.sleep(10)
pg.press('down')
pg.press('down')
pg.press('down')
pg.press('down')
pg.press('down')
pg.press('down')
pg.press('down')
pg.press('down')
pg.press('down')
pg.press('down')
pg.press('down')
pg.press('down')
pg.press('down')
pg.press('down')
pg.press('down')
pg.press('down')
pg.press('down')
pg.press('down')
pg.press('enter')
pg.sleep(1000)
pg.write('sudo apt update')
pg.write('y')
pg.press('enter')
pg.sleep(100)
pg.write('sudo apt install xrdp')
pg.sleep(10)
pg.write('y')
pg.press('enter')
pg.sleep(199)
pg.write('systemctl enable xrdp')