import pyautogui as pg
import time
time.sleep(6)
pg.hotkey('f11')
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.hotkey('tab')  
pg.keyDown('tab')
pg.keyDown('tab')
pg.hotkey('tab')    
pg.keyDown('tab')
time.sleep(2)
pg.write('ok bro!')                                         